### ISSUE TITLE
[S1 - PBI1] User dapat melakukan registrasi

### ISSUE THREAD

**Issue by farisslmn** [SI-RPL-2023/SI4406_F_ProfessionAble#1]

**Comment by Yosethimothy** [comment]
Registrasi adalah sebuah pelayanan pendaftaran setiap program yang berfungsi untuk menghubungkan data pribadi anda dengan program yang anda ikuti tersebut.
![image](https://user-images.githubusercontent.com/115619291/227876127-970c459e-768b-40cd-930c-36993cc04286.png)
