### ISSUE TITLE
[S1 - PBI4] User dapat mengakses halaman utama

### ISSUE THREAD

**Issue by farisslmn** [SI-RPL-2023/SI4406_F_ProfessionAble#4]

**Comment by azuraa61** [comment]
pada fitur ini user dapat mengakses ke menu halaman utama website ProfessionAble

**Comment by azuraa61** [comment]
![Beranda](https://user-images.githubusercontent.com/115639773/230304632-634fb412-5a25-406e-8858-ec6166905d07.png)
Berikut merupakan tampilan pada design halaman utama web ProfessionAble
