### ISSUE TITLE
[S1 - PBI5] Pelamar dapat melengkapi data diri

### ISSUE THREAD

**Issue by farisslmn** [SI-RPL-2023/SI4406_F_ProfessionAble#5]

**Comment by alamandaregitautami** [comment]
Dalam hal ini pelamar akan memasukkan beberapa data pribadi ke dalam website ProfessionAble

**Comment by farisslmn** [comment]
design profil
![Edit Profil](https://user-images.githubusercontent.com/115559173/230303702-a926d8f9-db39-4360-b7d0-11d9c75b5a77.png)
![Profil](https://user-images.githubusercontent.com/115559173/230303722-faf2c982-e782-4a23-b6e4-18aa467bdb9a.png)
